apiVersion: apps/v1
kind: Replicaset
metadata:
  name: customer
  labels:
    app: backend
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: customer
        image: 573567580560.dkr.ecr.ap-south-1.amazonaws.com/customer:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
